# Generated by Django 4.0.4 on 2022-05-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('front', '0002_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(choices=[], max_length=20, verbose_name='Category')),
                ('source', models.FileField(upload_to='', verbose_name='File')),
                ('difficulty', models.CharField(choices=[], max_length=10, verbose_name='Difficulty')),
            ],
        ),
    ]
