# Generated by Django 4.0.4 on 2022-05-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('pilates', 'Pilates'), ('yoga', 'Yoga'), ('dance', 'Dance')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('1.0', 'Easy'), ('3.0', 'Moderate'), ('5.0', 'Hard')], max_length=10, verbose_name='Difficulty'),
        ),
    ]
