# Generated by Django 4.0.4 on 2022-05-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_exercise_category_alter_exercise_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='star_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Star count'),
            preserve_default=False,
        ),
    ]
