# Generated by Django 4.0.4 on 2022-05-23 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0005_exercise_star_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('3', 'Moderate'), ('5', 'Hard')], max_length=10, verbose_name='Difficulty'),
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_histories', to='front.exercise', verbose_name='Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_histories', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
