# Generated by Django 4.0.4 on 2022-05-23 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_exercise_difficulty_exercisehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisehistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
