# Generated by Django 4.0.4 on 2022-05-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_exercisehistory_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisehistory',
            name='final_score',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Score'),
            preserve_default=False,
        ),
    ]
