# Generated by Django 4.0.4 on 2022-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_alter_exercisehistory_final_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='preview',
            field=models.ImageField(null=True, upload_to='', verbose_name='Preview Image'),
        ),
    ]
