# Generated by Django 4.0.4 on 2022-05-25 10:24

from django.db import migrations, models
import front.utils


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_exercise_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='preview',
            field=models.ImageField(null=True, upload_to=front.utils.FilenameChanger('media/preview/'), verbose_name='Preview Image'),
        ),
    ]
