# Generated by Django 4.0.4 on 2022-05-25 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_alter_exercise_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='exercisehistory',
            name='created',
        ),
        migrations.AddField(
            model_name='exercisehistory',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('workout', 'Workout'), ('pilates', 'Pilates'), ('yoga', 'Yoga'), ('dance', 'Dance')], max_length=20, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Score')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('exercise_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='front.exercisehistory', verbose_name='Exercise History')),
            ],
        ),
    ]
