# Generated by Django 4.0.4 on 2022-05-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisehistory',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='End'),
        ),
    ]
